export interface Report {
  act1Content: "",
  act2Content: "",
  mentorEmplNameHan: "권도균",
  act3Content: "",
  subject: "1120주제",
  expenseComment: "",
  act1Comment: "",
  remark: "",
  menteeEmplNameHan: "노태규",
  atchFileId: "",
  mentorOrgtx: "인사팀",
  coCode: "1000",
  feedbackMentor: "",
  belnr: "",
  planId: 55064,
  sapSndYn: "N",
  yyyyMm: "202411",
  comYnMentor: "",
  feedbackMentee: "",
  mentorTitleNameHan: "팀원",
  comYnMentee: "",
  mm: "11",
  mentorTitle: "팀원",
  menteeOrgNameHan: "인사팀",
  resultMentor: "",
  mentorOrgNameHan: "인사팀",
  expense: "",
  docNo: "",
  mentorEmplNo: "10003056",
  menteeTitleNameHan: "팀원",
  menteeEmplNo: "10006254",
  resultMentee: "",
  act2Comment: "",
  act3Comment: "",
  expenseSap: 0,
  gjahr: "",
  yyyy: "2024",
  finishDate: "20250301",
  startDate: "20241120",
  statusCode: ""
}

export interface Survey {
  
}