export interface EducationSurvey {
  examTypeCd: string,
  examSeq: number,
  examDateFrom: string,
  emplNo: string,
  emplNameHan: string,
  examDateRange: string,
  totPoints: string,
  examTimeFrom: string,
  examDateTo: string,
  examTake: string,
  eduSeq: string,
  eduTgtCnt: number,
  useYn: string,
  examTypeCdNm: string,
  examNm: string,
  eduQstCnt: number,
  btn: string,
  examTimeTo: string
}

export interface EducationReport {
  act1Content: string,
  act2Content: string,
  mentorEmplNameHan: string,
  act3Content: string,
  subject: string,
  expenseComment: string,
  act1Comment: string,
  remark: string,
  menteeEmplNameHan: string,
  atchFileId: string,
  mentorOrgtx: string,
  coCode: string,
  feedbackMentor: string,
  belnr: string,
  planId: number,
  sapSndYn: string,
  yyyyMm: string,
  comYnMentor: string,
  feedbackMentee: string,
  mentorTitleNameHan: string,
  comYnMentee: string,
  mm: string,
  mentorTitle: string,
  menteeOrgNameHan: string,
  resultMentor: string,
  mentorOrgNameHan: string,
  expense: string,
  docNo: string,
  mentorEmplNo: string,
  menteeTitleNameHan: string,
  menteeEmplNo: string,
  resultMentee: string,
  act2Comment: string,
  act3Comment: string,
  expenseSap: number,
  gjahr: string,
  yyyy: string,
  finishDate: string,
  startDate: string,
  statusCode: string
}




// export interface Report {
//   act1Content: "",
//   act2Content: "",
//   mentorEmplNameHan: "권도균",
//   act3Content: "",
//   subject: "1120주제",
//   expenseComment: "",
//   act1Comment: "",
//   remark: "",
//   menteeEmplNameHan: "노태규",
//   atchFileId: "",
//   mentorOrgtx: "인사팀",
//   coCode: "1000",
//   feedbackMentor: "",
//   belnr: "",
//   planId: 55064,
//   sapSndYn: "N",
//   yyyyMm: "202411",
//   comYnMentor: "",
//   feedbackMentee: "",
//   mentorTitleNameHan: "팀원",
//   comYnMentee: "",
//   mm: "11",
//   mentorTitle: "팀원",
//   menteeOrgNameHan: "인사팀",
//   resultMentor: "",
//   mentorOrgNameHan: "인사팀",
//   expense: "",
//   docNo: "",
//   mentorEmplNo: "10003056",
//   menteeTitleNameHan: "팀원",
//   menteeEmplNo: "10006254",
//   resultMentee: "",
//   act2Comment: "",
//   act3Comment: "",
//   expenseSap: 0,
//   gjahr: "",
//   yyyy: "2024",
//   finishDate: "20250301",
//   startDate: "20241120",
//   statusCode: ""
// }