export type Menu = {
  // loginCoId: string,
  // loginCoNm: string,
  // loginCoEngNm: string,
  // loginUserId: string,
  // loginUserNm: string,
  // loginDeptId: string,
  // loginDeptName: string,
  // loginIdntClCode: string,
  // loginTitleCode: string,
  // loginTitleName: string,
  // loginPstnName: string,
  // loginGradeName: string,
  // loginEntranceDate: string,
  // loginRetireDate?: string,
  // loginCellularTel: string,
  // loginInitPwdYn?: string,
  // loginPwResetDt: string,
  // rowStatus: string,
  // chk: boolean,
  menuId: number,
  menuNm: string,
  // pgmId?: number,
  // pgmNm?: number,
  // uprMenuId: number,
  // lvlCod?: string,
  // menuUseAt: string,
  menuTyCod?: string,
  // menuSrtOd: string,
  // menuTypeCode?: string,
  // pgmMarkAt?: string,
  // pgmUrlAd?: string,
  // pgmLinkAt?: string,
  // relBizCod: string,
  // favPgmAt: string,
  // mobileUseAt: string,
  // topCss?: string,
  // active?: string,
  // open?: string,
  // url?: string,
  // menuList?: string,
  // roleIds?: string
  menuList: [
    {
      mobileUseAt: string,
      menuUseAt: string,
      menuNm: string,
    }
  ],
}